Is100 8
e-sau/step-by-step pull request #34
Opened 2020-11-19 02:32 UTC by KholmanovAndrey

Добавил миграцию на добавление столбца тип задания (type->unique) и обновил модель Task под новый параметр

2020-11-19 06:08 UTC, e-sau requested changes
Предложение было типы заданий вынести в отдельную таблицу, а в тасках сделать ссылку

2020-11-19 10:35 UTC, Cheefs commented
> Предложение было типы заданий вынести в отдельную таблицу, а в тасках сделать ссылку

Это я поставил задачу криво, говорил и описывал от лица фронта, забыв о беке, поэтому вышло недопонимание, но Андрей поправил, по моему все ок )

Только конфликт какой то вылез

2020-11-19 10:57 UTC, e-sau reviewed
Конфликт из-за контроллера, в ветке нет моих изменений. Теперь ответы на get запросы формируются через ресурсы

2020-11-19 10:57 UTC, e-sau commented on app/Http/Controllers/Api/TaskController.php
> +        $task->type = $task->type->name;
Так не надо делать. Это прописывается в ресурсе.

2020-11-19 10:57 UTC, e-sau commented on app/Models/Task.php
> +        'title', 'description', 'difficult', 'solution', 'subject_id', 'type'
Должно быть тогда type_id

2020-11-19 10:57 UTC, e-sau commented on app/Models/TaskType.php
> +}
надо добавить связь one to many

2020-11-19 11:25 UTC, KholmanovAndrey commented on app/Http/Controllers/Api/TaskController.php
> +        $task->type = $task->type->name;
понял поправлю

2020-11-19 11:26 UTC, KholmanovAndrey commented on app/Models/Task.php
> +        'title', 'description', 'difficult', 'solution', 'subject_id', 'type'
косяк. забыл поправить

2020-11-20 12:42 UTC, Cheefs approved these changes

2020-11-22 09:55 UTC, e-sau commented
PR закрываю. Перебазировал ветку dev на последние изменения

2020-11-22 09:55 UTC, closed without merging